# proyectoFinal/docker-compose.yml:

version: '3.8'
services:
  frontend:
    build:
      context: ./FrontEndReact
      dockerfile: Dockerfile
    ports:
      - "8383:8383" 
    networks:
      - mynetwork
    depends_on:
      - backend

  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_backend_express
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    build:
      context: ./BackendExpressJS
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/db_backend_express
    networks:
      - mynetwork
    depends_on:
      - db

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: